"""Store screenshot captions, one line per scene, in the order of locales.SCENES:
focus, mix, timer, sleep, settings."""

CAPTIONS = {
"en": ["Brown noise that never loops", "Blend nine sounds into your mix", "Sleep timer with a slow fade", "For focus, sleep and babies", "No ads. No accounts. Offline."],
"de": ["Braunes Rauschen ohne Schleife", "Neun Klänge zu deinem Mix", "Einschlaf-Timer mit sanftem Ausblenden", "Für Fokus, Schlaf und Babys", "Keine Werbung. Keine Konten. Offline."],
"fr": ["Un bruit brun sans boucle", "Neuf sons pour votre mélange", "Minuteur de sommeil en fondu", "Concentration, sommeil, bébés", "Sans pub. Sans compte. Hors ligne."],
"es": ["Ruido marrón sin bucles", "Mezcla nueve sonidos a tu gusto", "Temporizador con fundido suave", "Para concentrarte, dormir y bebés", "Sin anuncios ni cuentas. Sin conexión."],
"it": ["Rumore marrone senza loop", "Mixa nove suoni a modo tuo", "Timer del sonno con dissolvenza", "Per concentrazione, sonno e neonati", "Senza pubblicità né account. Offline."],
"pt-BR": ["Ruído marrom sem repetição", "Misture nove sons do seu jeito", "Timer de sono com fade suave", "Para foco, sono e bebês", "Sem anúncios nem contas. Offline."],
"pt-PT": ["Ruído castanho sem repetição", "Misture nove sons à sua maneira", "Temporizador com esbatimento suave", "Para concentração, sono e bebés", "Sem anúncios nem contas. Offline."],
"nl": ["Bruine ruis zonder lus", "Meng negen geluiden tot jouw mix", "Slaaptimer met zacht vervagen", "Voor focus, slaap en baby's", "Geen advertenties. Geen accounts. Offline."],
"sv": ["Brunt brus som aldrig loopar", "Blanda nio ljud till din mix", "Sovtimer med mjuk uttoning", "För fokus, sömn och bebisar", "Inga annonser. Inga konton. Offline."],
"da": ["Brun støj uden gentagelser", "Bland ni lyde til din egen mix", "Sovetimer med blød udtoning", "Til fokus, søvn og babyer", "Ingen reklamer. Ingen konti. Offline."],
"nb": ["Brunt støy uten løkker", "Bland ni lyder til din egen miks", "Sovetimer med myk uttoning", "For fokus, søvn og babyer", "Ingen reklame. Ingen kontoer. Offline."],
"fi": ["Ruskea kohina ilman silmukkaa", "Yhdeksän ääntä, oma miksisi", "Uniajastin pehmeällä häivytyksellä", "Keskittymiseen, uneen ja vauvoille", "Ei mainoksia. Ei tilejä. Offline."],
"pl": ["Brązowy szum bez zapętlenia", "Połącz dziewięć dźwięków w swój miks", "Timer snu z płynnym wyciszaniem", "Do skupienia, snu i dla niemowląt", "Bez reklam. Bez kont. Offline."],
"cs": ["Hnědý šum bez smyčky", "Smíchejte devět zvuků po svém", "Časovač spánku s plynulým zeslabením", "Pro soustředění, spánek i miminka", "Bez reklam. Bez účtů. Offline."],
"sk": ["Hnedý šum bez opakovania", "Zmiešajte deväť zvukov po svojom", "Časovač spánku s plynulým stíšením", "Na sústredenie, spánok aj bábätká", "Bez reklám. Bez účtov. Offline."],
"hu": ["Barna zaj ismétlődés nélkül", "Keverj össze kilenc hangot", "Elalvás időzítő lágy elhalkulással", "Fókuszhoz, alváshoz, babáknak", "Nincs reklám. Nincs fiók. Offline."],
"ro": ["Zgomot maro fără repetiții", "Amestecă nouă sunete după gust", "Temporizator de somn cu estompare", "Pentru concentrare, somn și bebeluși", "Fără reclame. Fără conturi. Offline."],
"hr": ["Smeđi šum bez ponavljanja", "Pomiješaj devet zvukova po želji", "Timer za spavanje s blagim stišavanjem", "Za fokus, san i bebe", "Bez oglasa. Bez računa. Izvan mreže."],
"ca": ["Soroll marró sense bucles", "Barreja nou sons al teu gust", "Temporitzador amb esvaïment suau", "Per concentrar-te, dormir i nadons", "Sense anuncis ni comptes. Sense connexió."],
"el": ["Καφέ θόρυβος χωρίς επανάληψη", "Ανάμειξε εννέα ήχους στα μέτρα σου", "Χρονόμετρο ύπνου με απαλό σβήσιμο", "Για συγκέντρωση, ύπνο και μωρά", "Χωρίς διαφημίσεις και λογαριασμούς. Εκτός σύνδεσης."],
"tr": ["Döngüsüz kahverengi gürültü", "Dokuz sesi kendi karışımına dönüştür", "Yumuşak kısılan uyku zamanlayıcısı", "Odak, uyku ve bebekler için", "Reklam yok. Hesap yok. Çevrimdışı."],
"ru": ["Коричневый шум без повторов", "Девять звуков в вашем миксе", "Таймер сна с плавным затуханием", "Для фокуса, сна и малышей", "Без рекламы и аккаунтов. Офлайн."],
"uk": ["Коричневий шум без повторів", "Дев’ять звуків у вашому міксі", "Таймер сну з плавним згасанням", "Для фокусу, сну й малюків", "Без реклами й акаунтів. Офлайн."],
"ar": ["ضجيج بني بلا تكرار", "امزج تسعة أصوات على ذوقك", "مؤقّت نوم مع تلاشٍ هادئ", "للتركيز والنوم والأطفال", "بلا إعلانات ولا حسابات. دون اتصال."],
"he": ["רעש חום בלי לולאות", "ערבבו תשעה צלילים למיקס שלכם", "טיימר שינה עם עמעום הדרגתי", "לריכוז, לשינה ולתינוקות", "בלי פרסומות ובלי חשבונות. לא מקוון."],
"hi": ["बिना दोहराव वाला ब्राउन नॉइज़", "नौ ध्वनियों से बनाएँ अपना मिक्स", "धीमे फ़ेड वाला स्लीप टाइमर", "फ़ोकस, नींद और शिशुओं के लिए", "न विज्ञापन, न अकाउंट। ऑफ़लाइन।"],
"th": ["เสียงรบกวนสีน้ำตาลที่ไม่วนซ้ำ", "ผสมเก้าเสียงเป็นมิกซ์ของคุณ", "ตั้งเวลานอนพร้อมเสียงค่อย ๆ เบาลง", "สำหรับโฟกัส การนอน และเด็กทารก", "ไม่มีโฆษณา ไม่มีบัญชี ออฟไลน์"],
"vi": ["Tiếng ồn nâu không lặp lại", "Trộn chín âm thanh theo ý bạn", "Hẹn giờ ngủ với âm nhỏ dần", "Cho tập trung, giấc ngủ và em bé", "Không quảng cáo. Không tài khoản. Ngoại tuyến."],
"id": ["Derau cokelat tanpa pengulangan", "Campur sembilan suara sesukamu", "Timer tidur dengan pemudaran halus", "Untuk fokus, tidur, dan bayi", "Tanpa iklan. Tanpa akun. Offline."],
"ms": ["Bunyi coklat tanpa ulangan", "Campur sembilan bunyi mengikut citarasa", "Pemasa tidur dengan pudar lembut", "Untuk fokus, tidur dan bayi", "Tiada iklan. Tiada akaun. Luar talian."],
"ja": ["ループしないブラウンノイズ", "9つの音を自分好みにミックス", "ゆっくりフェードするスリープタイマー", "集中、睡眠、赤ちゃんのために", "広告なし。アカウント不要。オフライン。"],
"ko": ["반복 없는 브라운 노이즈", "아홉 가지 소리를 나만의 믹스로", "서서히 줄어드는 수면 타이머", "집중, 수면, 아기를 위해", "광고 없음. 계정 없음. 오프라인."],
"zh-Hans": ["永不循环的布朗噪声", "九种声音，混出你的专属音效", "缓缓淡出的睡眠定时器", "专注、睡眠、哄睡宝宝", "无广告，无账户，离线可用"],
"zh-Hant": ["永不循環的布朗噪音", "九種聲音，混出專屬音效", "緩緩淡出的睡眠計時器", "專注、睡眠、哄寶寶入睡", "無廣告、無帳號、離線可用"],
}
